### PR TITLE
Mapimage

### PR DESCRIPTION
**Pull request by rbbri**
Updates map. 1 Jest test is failing due to gamepage snapshot. Cypress tests need to be changed

### CODE REVIEW

**Comment by runticle** [comment]
run tests and press u to fix the snapshot?

I don't mind branching into it and fixing that unless you wanna

**Comment by rbbri** [comment]
> run tests and press u to fix the snapshot?
> 
> I don't mind branching into it and fixing that unless you wanna

Snapshot fixed but different error with gamepage. Still having intermittent issues with signs after fixing and merging

**Comment by rbbri** [comment]
Branch on

**Comment by runticle** [comment]
was missing an import

**Comment by runticle** [comment]
have fixed it

**Pull request merged**
